apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment
  targetCPUUtilizationPercentage: 35
--- # HPA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
    # deployment distribution
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: hemgistry.azurecr.io/hampress
          name: wordpress
          env:
            - name: WORDPRESS_DB_NAME
              value: hemdb
            - name: WORDPRESS_DB_USER
              value: hamster@hem-db-server
            - name: WORDPRESS_DB_HOST
              value: 10.0.0.44 #hem-db-server.mysql.database.azure.com
            - name: WORDPRESS_DB_PASSWORD
              value: q1q1q1q1q1q!
              # wordpress wp-config.php
          ports:
            - containerPort: 80
              name: wordpress
          resources:
            requests:
              memory: "990Mi"
              cpu: "990m"
            limits:
              memory: "990Mi"
              cpu: "990m"
              # hpa resource
          volumeMounts:
            - name: volume # azurefile, volume
              mountPath: /var/www/html
              # pvc mount
      volumes:
        - name: volume # azurefile, volume
          persistentVolumeClaim:
            claimName: azure-hamtorage # PVC name
