apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
    # deployment distribution
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_NAME
              value: newham
            - name: WORDPRESS_DB_USER
              value: azureuser@hamster-db
            - name: WORDPRESS_DB_HOST
              value: hamster-db.mysql.database.azure.com
            - name: WORDPRESS_DB_PASSWORD
              value: q1q1q1q1q1q!
              # wordpress wp-config.php
          ports:
            - containerPort: 80
              name: wordpress
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "400m"
              # hpa resource
          volumeMounts:
            - name: volume # azurefile, volume
              mountPath: /var/www/html
              # pvc mount
      volumes:
        - name: volume # azurefile, volume
          persistentVolumeClaim:
            claimName: azure-hamster-disk # PVC name
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-hamster-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  # Kind
  resources:
    requests:
      storage: 5Gi
