apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:4.8-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_NAME
              value: hamster
            - name: WORDPRESS_DB_USER
              value: azureuser@hamster-db
            - name: WORDPRESS_DB_HOST
              value: hamster-db.mysql.database.azure.com
            - name: WORDPRESS_DB_PASSWORD
              value: q1q1q1q1q1q!
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: azuredisk
              mountPath: /var/www/html
      volumes:
        - name: azuredisk
          persistentVolumeClaim:
            claimName: azure-hamster-disk # PVC name
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-hamster-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default # Standard : default , Premium : managed-premium
  resources:
    requests:
      storage: 5Gi
